### PR TITLE
Sr omnibot simtest

### PR DESCRIPTION
**Pull request by Shah-Rajab**
Playing around with the simulation of the omnibot.

### CODE REVIEW

**Comment by Vuwij** [comment]
This pull request **introduces 12 alerts** when merging 9b0670ea72d0ac500ba837312fe445c5383ff2b5 into 3f7828ff78cb725007388ff58d6137ca08ececd8 - [view on LGTM.com](https://lgtm.com/projects/g/utra-robosoccer/soccer_ws/rev/pr-2b1118c4e1da27c121446f52d3c3319da514932f)

**new alerts:**

* 7 for Unused import
* 4 for Unused local variable
* 1 for Testing equality to None

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Vuwij** [comment]
You can click on the CI for details

**Comment by Vuwij** [comment]
Why is this not building?

**Comment by Shah-Rajab** [comment]
> Why is this not building?

I think the keys for apt needs to be renewed.

**Comment by Vuwij** [comment]
Why is it not building for you?

Regards, 
Jason Wang, Computer Eng. Student
Tel: 647-879-4660 | Skype: Jaw.vuwij

**Pull request closed without merging**
