### PR TITLE
WIP: Configure catkin to lint pedantically

### PR DESCRIPTION
**Pull request by HPrickettMorgan**

### CODE REVIEW

**Comment by HPrickettMorgan** [comment]
catkin_lint has identified a number of problems with our package organization. These should be fixed and passing these checks should be required to ensure high quality code and good organization.

Not sure what to do about darknet_ros having so many issues yet...

**Comment by Vuwij** [comment]
This is pretty good. Just make changes you think can fix it.

**Comment by HPrickettMorgan** [comment]
@Vuwij https://answers.ros.org/question/239594/ros_control-cannot-be-found-kinetic/ seems to suggest that depending on a metapackage is bad practice from a catkin perspective. Can you clarify what we're actually depending on/point me to whoever maintains soccer_description so we can properly break out the dependencies.

**Comment by Vuwij** [comment]
Sure. Must be one of the lints. I'll help figure it out

**Pull request closed without merging**
